- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: Install python-passlib
  apt:
    name: python-passlib
    state: latest
  when: nginx_htpasswd

- name: Add nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Add nginx mime types
  template:
    src: mime.types.j2
    dest: /etc/nginx/mime.types
  notify: restart nginx

- name: Add sites
  template:
    src: "sites/{{item.name}}.j2"
    dest: "/etc/nginx/sites-available/{{item.name}}"
  with_items: nginx_sites
  notify: reload nginx

- name: Remove sites
  file:
    path: "/etc/nginx/sites-available/{{item.name}}"
    state: absent
  with_items: nginx_sites_remove
  notify: reload nginx

- name: Add site directories
  file:
    path: "/var/www/{{item.name}}"
    state: directory
  with_flattened:
    - nginx_sites
    - nginx_directories

- name: Remove site directories
  file:
    path: "/var/www/{{item}}"
    state: absent
  with_items:
    - nginx_sites_remove
    - nginx_directories_remove

- name: Enable sites
  file:
    path: "/etc/nginx/sites-enabled/{{item}}"
    src: "/etc/nginx/sites-available/{{item}}"
    state: link
  with_items: nginx_sites_enabled
  notify: reload nginx

- name: Disable sites
  file:
    path: "/etc/nginx/sites-enabled/{{item}}"
    state: absent
  with_items: nginx_sites_disabled
  notify: reload nginx

- name: Add htpasswd entries
  htpasswd:
    name: "{{item.name}}"
    password: "{{item.password}}"
    path: /etc/nginx/.htpasswd
    state: present
  with_items: nginx_htpasswd
