- name: Gather initial information
  hosts: app-base
  tasks:
    - name: Ansible environment - sudo user
      debug:
        var: ansible_env.SUDO_USER
    - name: Ansible environment - user
      debug:
        var: ansible_env.USER

- name: Apply base tasks
  hosts: app-base
  roles:
    - timezone
    - ntp
    - users
    - hostname
    - apt
    - openssh
    - updates
    - dns
