ntp_driftfile: "/var/lib/ntp/ntp.drift"
ntp_statsdir: "/var/log/ntpstats/"
ntp_leapurl: "http://www.ietf.org/timezones/data/leap-seconds.list"
ntp_leapfile: "/etc/ntp.leapseconds"

ntp_servers:
  - "0.pool.ntp.org"
  - "1.pool.ntp.org"
  - "2.pool.ntp.org"
  - "3.pool.ntp.org"

ntp_restricts:
  - "restrict -4 default kod notrap nomodify nopeer noquery"
  - "restrict -6 default kod notrap nomodify nopeer noquery"
  - "restrict 127.0.0.1"
  - "restrict ::1"
