- name: Install OpenSSH
  apt:
    pkg: "{{item}}"
    state: present
  with_items: 
    - openssh-client
    - openssh-server

- name: Configure OpenSSH Client
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644

- name: Configure OpenSSH Server
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ssh
