- name: Install jekyll
  gem:
    name: jekyll
    state: latest

- name: Download jekyll sites
  git:
    repo: "{{item.repo}}"
    dest: "{{item.path}}"
    force: yes
    accept_hostkey: yes
  with_items: jekyll_sites
  notify: restart jekyll

- name: Add systemd services
  template:
    src: jekyll.service.j2
    dest: "/etc/systemd/system/jekyll-{{item.name}}.service"
  with_items: jekyll_sites
  notify:
    - reload systemd
    - restart jekyll

- name: Start services
  service:
    name: "jekyll-{{item.name}}"
    state: started
    enabled: yes
  with_items: jekyll_sites
