- name: Make sure tzdata is installed
  apt:
    name: tzdata
    state: present

- name: Update /etc/timezone
  template:
    src: timezone.j2
    dest: /etc/timezone

- name: Symlink the correct localtime
  file:
    src: /usr/share/zoneinfo/{{timezone_zone}}
    dest: /etc/localtime
    state: link
    owner: root
    group: root
    mode: 0644
    force: yes
  changed_when: False
  notify: update timezone
